### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by AlphaBrock** [qiangzi7723/spider-for-netease-music#8]
`/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'name' of undefined
    at query (/home/alphabrock/file/spider-for-netease-music/spider/code/song.js:30:37)
    at Query.conn.query [as _callback] (/home/alphabrock/file/spider-for-netease-music/spider/mysql/index.js:11:17)
    at Query.Sequence.end (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/alphabrock/file/spider-for-netease-music/spider/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)`

> 这是什么一个情况呢

**Comment by Alone95** [comment]
我也有这一问题，求解

**Comment by xiaoshidebaiyuhui** [comment]
我也遇到这个问题，作者可以把建立的数据库，发出来看看吗

**Comment by Braveleon** [comment]
同碰到这个问题，解决了？有能回答下的不

**Comment by qiangzi7723** [comment]
已经修复。
